services:
  - type: web
    name: mente-azul
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: redirect
        source: /*
        destination: /index.html